# This file was generated by GoReleaser. DO NOT EDIT.
cask "f5xcctl" do
  name "f5xcctl"
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://robinmordasiewicz.github.io/f5xcctl"
  version "4.37.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "f5xcctl"
  bash_completion "completions/f5xcctl.bash"
  zsh_completion "completions/f5xcctl.zsh"
  fish_completion "completions/f5xcctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_darwin_amd64.tar.gz"
      sha256 "7515f764a38858970dfc5c76f415eb94860ebe9b5a7b96fb734920745ed8296e"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_darwin_arm64.tar.gz"
      sha256 "762f11663dcea25f318ab0a0aeaa32887173c2d2324147fdc53fe290762f7b67"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_linux_amd64.tar.gz"
      sha256 "c2d02f6af62dd309cc8fdc71a8bf1fcdabcb7c168d3f84c54f1e5a4d468b20de"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_linux_arm64.tar.gz"
      sha256 "cdfc85b629d09aedfd153d4896bcf7fad19d441f24c76f03d61e2c0e10835595"
    end
  end

  caveats <<~EOS
    Shell completions have been installed for bash, zsh, and fish.

    For setup instructions, see:
      https://robinmordasiewicz.github.io/f5xcctl/install/homebrew/#shell-completions

    Quick start:
      Zsh: Usually works automatically. Restart your terminal.
      Bash: Run 'brew install bash-completion@2' first.
      Fish: Works automatically.

    Test with: f5xcctl [TAB]
  EOS
end
