# This file was generated by GoReleaser. DO NOT EDIT.
cask "f5xcctl" do
  name "f5xcctl"
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://robinmordasiewicz.github.io/f5xcctl"
  version "4.40.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "f5xcctl"
  bash_completion "completions/f5xcctl.bash"
  zsh_completion "completions/f5xcctl.zsh"
  fish_completion "completions/f5xcctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_darwin_amd64.tar.gz"
      sha256 "c9edc3e21f53dcc22e7c7c2bd02bac3b9703aef38ac9eab25cb72a23a517e60e"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_darwin_arm64.tar.gz"
      sha256 "478767a585dbe5677b378a23d096780cc06afa3405f3b9beab32a91f08d0c1f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_linux_amd64.tar.gz"
      sha256 "0a73522a9a76f6ee36521bfceddc7eda6dae1181a383902764a178581e68771c"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_linux_arm64.tar.gz"
      sha256 "9dab219b83704d48c766938dcfce4c52a4b6de5ce2836c52e158068d43f5261b"
    end
  end

  caveats do
    "Shell completions have been installed for bash, zsh, and fish."
    ""
    "For setup instructions, see:"
    "  https://robinmordasiewicz.github.io/f5xcctl/install/homebrew/#shell-completions"
    ""
    "Quick start:"
    "  Zsh: Usually works automatically. Restart your terminal."
    "  Bash: Run 'brew install bash-completion@2' first."
    "  Fish: Works automatically."
    ""
    "Test with: f5xcctl [TAB]"
  end

  # No zap stanza required
end
