# This file was generated by GoReleaser. DO NOT EDIT.
cask "f5xcctl" do
  name "f5xcctl"
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://robinmordasiewicz.github.io/f5xcctl"
  version "4.27.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "f5xcctl"
  bash_completion "completions/f5xcctl.bash"
  zsh_completion "completions/f5xcctl.zsh"
  fish_completion "completions/f5xcctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_darwin_amd64.tar.gz"
      sha256 "5975f65f35b392b2c31de7707e9f807452afc70b1c930ebcd8cd7b29fedd91af"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_darwin_arm64.tar.gz"
      sha256 "19f9f7661ebbf9a90455fdffce3b3bf10b06d48343a1907ddff74b68543423b9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_linux_amd64.tar.gz"
      sha256 "4ec226138888e37aad132220215a29c9143926497b24737862cb323a0a35cd03"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v#{version}/f5xcctl_#{version}_linux_arm64.tar.gz"
      sha256 "faa5d04cb3b8c9f107a295d6ae032cad543d6efed0cc92d699b3ee8cde5da7ff"
    end
  end

  caveats <<~EOS
    Shell completions have been installed for bash, zsh, and fish.

    For setup instructions, see:
      https://robinmordasiewicz.github.io/f5xcctl/install/homebrew/#shell-completions

    Quick start:
      Zsh: Usually works automatically. Restart your terminal.
      Bash: Run 'brew install bash-completion@2' first.
      Fish: Works automatically.

    Test with: f5xcctl [TAB]
  EOS
end
