# This file was generated by GoReleaser. DO NOT EDIT.
cask "vesctl" do
  name "vesctl"
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://robinmordasiewicz.github.io/vesctl"
  version "4.15.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vesctl"

  on_macos do
    on_intel do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_darwin_amd64.tar.gz"
      sha256 "5d09be4b7b6b9639338f7c00bc281996cd429c1cfe115e41b680dbc3b6139a5c"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_darwin_arm64.tar.gz"
      sha256 "ed06076ed7cd689726113991dd2d21060f0cd0e2a21f983648709db6e10665cb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_linux_amd64.tar.gz"
      sha256 "10bece65333d979f21f03a907b537e764eb37f0a2580ea023d779e71b2984ac8"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_linux_arm64.tar.gz"
      sha256 "2f066dba8a3a8df916e4ab82d318164b221088ef85c6be99e4cd552e6ec142b8"
    end
  end

  # No zap stanza required
end
