# This file was generated by GoReleaser. DO NOT EDIT.
cask "vesctl" do
  name "vesctl"
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://robinmordasiewicz.github.io/vesctl"
  version "4.17.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vesctl"
  bash_completion "completions/vesctl.bash"
  zsh_completion "completions/vesctl.zsh"
  fish_completion "completions/vesctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_darwin_amd64.tar.gz"
      sha256 "5634312c2712027cfbdd6204af6df79817189453a0c57abd8c4eadb6e41d1e9f"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_darwin_arm64.tar.gz"
      sha256 "dc8c35ea23c84e1b538cfce83736ab5166307b60830cbf4dee8fd4e014cf4a3c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_linux_amd64.tar.gz"
      sha256 "bdbb10bd1ff282b8cd06285c860f14a53de7ff0f0f0ec6078b3a9187867ffed9"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_linux_arm64.tar.gz"
      sha256 "e6c101790e58270286731ce847038cb7ec1c777fb09c876292527b400e15ec1f"
    end
  end

  caveats do
    "Shell completions have been installed for bash, zsh, and fish."
    ""
    "For setup instructions, see:"
    "  https://robinmordasiewicz.github.io/vesctl/install/homebrew/#shell-completions"
    ""
    "Quick start:"
    "  Zsh: Usually works automatically. Restart your terminal."
    "  Bash: Run 'brew install bash-completion@2' first."
    "  Fish: Works automatically."
    ""
    "Test with: vesctl [TAB]"
  end

  # No zap stanza required
end
