# This file was generated by GoReleaser. DO NOT EDIT.
cask "vesctl" do
  name "vesctl"
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://robinmordasiewicz.github.io/vesctl"
  version "4.16.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vesctl"
  bash_completion "completions/vesctl.bash"
  zsh_completion "completions/vesctl.zsh"
  fish_completion "completions/vesctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_darwin_amd64.tar.gz"
      sha256 "eecbb368b24b316be67b42bcebef6a11641a66e878eb68a844324b3d9bcaf8a2"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_darwin_arm64.tar.gz"
      sha256 "6b2c8d653089ed94eccb99523589bbddb052a05c19a066818cd8909c7b84d932"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_linux_amd64.tar.gz"
      sha256 "92fcc6ea50c77669bb18ccd4634387cf1c857fd6c49425344f9b4bd44c4b6cc4"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v#{version}/vesctl_#{version}_linux_arm64.tar.gz"
      sha256 "ee8aa2af8a93a57f2c0a1db947cebbbc1c8d6c97f3ae214ae345d062bd556588"
    end
  end

  caveats do
    "Shell completions have been installed for bash, zsh, and fish."
    ""
    "For setup instructions, see:"
    "  https://robinmordasiewicz.github.io/vesctl/install/homebrew/#shell-completions"
    ""
    "Quick start:"
    "  Zsh: Usually works automatically. Restart your terminal."
    "  Bash: Run 'brew install bash-completion@2' first."
    "  Fish: Works automatically."
    ""
    "Test with: vesctl [TAB]"
  end

  # No zap stanza required
end
