# This file was generated by GoReleaser. DO NOT EDIT.
cask "xcsh" do
  name "xcsh"
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://robinmordasiewicz.github.io/xcsh"
  version "5.21.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xcsh"
  bash_completion "completions/xcsh.bash"
  zsh_completion "completions/xcsh.zsh"
  fish_completion "completions/xcsh.fish"

  on_macos do
    on_intel do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_darwin_amd64.tar.gz"
      sha256 "6549c6ea1448444fc1adb8988b4421d3979cfa3a2d91360ccdd7f02c5100e824"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_darwin_arm64.tar.gz"
      sha256 "d5c859c1e55460c9c6130eccf58598716d7c48f9d5d809df791c63abe8bbe464"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_linux_amd64.tar.gz"
      sha256 "e6389b1bed37c134ea0a11d14a354bb91f42f1c6eab015d6cdd8504c1bcdf857"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_linux_arm64.tar.gz"
      sha256 "9f534ac302e4588c4e8cd7950e89938bb7dcab7ac4fbb4d0112245cbcc6a991e"
    end
  end

  caveats do
    "Shell completions have been installed for bash, zsh, and fish."
    ""
    "For setup instructions, see:"
    "  https://robinmordasiewicz.github.io/xcsh/install/homebrew/#shell-completions"
    ""
    "Quick start:"
    "  Zsh: Usually works automatically. Restart your terminal."
    "  Bash: Run 'brew install bash-completion@2' first."
    "  Fish: Works automatically."
    ""
    "Test with: xcsh [TAB]"
  end

  # No zap stanza required
end
