# This file was generated by GoReleaser. DO NOT EDIT.
cask "xcsh" do
  name "xcsh"
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://robinmordasiewicz.github.io/xcsh"
  version "5.32.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xcsh"
  bash_completion "completions/xcsh.bash"
  zsh_completion "completions/xcsh.zsh"
  fish_completion "completions/xcsh.fish"

  on_macos do
    on_intel do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_darwin_amd64.tar.gz"
      sha256 "d81edb7fb6e569713fba3f6cac00a2600a673718c29244e1addacb20bb505db1"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_darwin_arm64.tar.gz"
      sha256 "12cbc09a8f7eee2b1bdbd9ba84134754c0a1695ad0c41677b57aa3ca8780f61e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_linux_amd64.tar.gz"
      sha256 "8f3ab1cee1e987eb9ccf8784542588972441274a82be6ce21148c3c9676466a5"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_linux_arm64.tar.gz"
      sha256 "e33562a6bd5ac4640efac707b2d4054af24cc5ab750b9f09ecd563a017a84d1f"
    end
  end

  # Clear zsh completion cache after install/upgrade
  postflight do
    system_command "/bin/rm", args: ["-f", "#{Dir.home}/.zcompdump", "#{Dir.home}/.zcompdump-#{Socket.gethostname}-*"]
  end

  caveats <<~EOS
    Shell completions have been installed for bash, zsh, and fish.

    For setup instructions, see:
      https://robinmordasiewicz.github.io/xcsh/install/homebrew/#shell-completions

    Quick start:
      Zsh: Usually works automatically. Restart your terminal.
      Bash: Run 'brew install bash-completion@2' first.
      Fish: Works automatically.

    Test with: xcsh [TAB]
  EOS
end
