# This file was generated by GoReleaser. DO NOT EDIT.
cask "xcsh" do
  name "xcsh"
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://robinmordasiewicz.github.io/xcsh"
  version "5.23.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "xcsh"
  bash_completion "completions/xcsh.bash"
  zsh_completion "completions/xcsh.zsh"
  fish_completion "completions/xcsh.fish"

  on_macos do
    on_intel do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_darwin_amd64.tar.gz"
      sha256 "668361c544e23c5ca8d09b3b0fb6933790415aca23a6850602eef55ea0cbc196"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_darwin_arm64.tar.gz"
      sha256 "c7f398af7898dfe509980510c25b9ece51b32969a8c1bb22f68c120445eb6ec5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_linux_amd64.tar.gz"
      sha256 "2e42d84e61e708bd49e2f7e16c3618c48e20836a5188eaa9f7698457160afa68"
    end
    on_arm do
      url "https://github.com/robinmordasiewicz/xcsh/releases/download/v#{version}/xcsh_#{version}_linux_arm64.tar.gz"
      sha256 "f3e367d30e54213e3396ec0199dc82083aea16da2731bf72303324786fde0d98"
    end
  end

  # Clear zsh completion cache after install/upgrade
  postflight do
    system_command "/bin/rm", args: ["-f", "#{Dir.home}/.zcompdump", "#{Dir.home}/.zcompdump-#{Socket.gethostname}-*"]
  end

  caveats <<~EOS
    Shell completions have been installed for bash, zsh, and fish.

    For setup instructions, see:
      https://robinmordasiewicz.github.io/xcsh/install/homebrew/#shell-completions

    Quick start:
      Zsh: Usually works automatically. Restart your terminal.
      Bash: Run 'brew install bash-completion@2' first.
      Fish: Works automatically.

    Test with: xcsh [TAB]
  EOS
end
