# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class F5xcctl < Formula
  desc "kubectl-style CLI for F5 Distributed Cloud"
  homepage "https://github.com/robinmordasiewicz/f5xcctl"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v0.1.3/f5xcctl_0.1.3_darwin_amd64.tar.gz"
      sha256 "d9b49319846950da33bc41a83ae88589ecd30dbd074b4259047c02fc8dd85bb5"

      def install
        bin.install "f5xcctl"
        bash_completion.install "completions/f5xcctl.bash" => "f5xcctl"
        zsh_completion.install "completions/_f5xcctl"
        fish_completion.install "completions/f5xcctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v0.1.3/f5xcctl_0.1.3_darwin_arm64.tar.gz"
      sha256 "e5244b21738b95785aa282a82aa37c1ef20ea04af559ee50868ca38b3fbdb697"

      def install
        bin.install "f5xcctl"
        bash_completion.install "completions/f5xcctl.bash" => "f5xcctl"
        zsh_completion.install "completions/_f5xcctl"
        fish_completion.install "completions/f5xcctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v0.1.3/f5xcctl_0.1.3_linux_amd64.tar.gz"
      sha256 "ad700b29b6541c96062dbc441920bc3b36106dbc42f4f6b6c29dc141ebaf4604"
      def install
        bin.install "f5xcctl"
        bash_completion.install "completions/f5xcctl.bash" => "f5xcctl"
        zsh_completion.install "completions/_f5xcctl"
        fish_completion.install "completions/f5xcctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v0.1.3/f5xcctl_0.1.3_linux_arm64.tar.gz"
      sha256 "06d0d39837219fa5f5cdabdd97849588d0db5903567fcfdbbd52c6f3e3e6394a"
      def install
        bin.install "f5xcctl"
        bash_completion.install "completions/f5xcctl.bash" => "f5xcctl"
        zsh_completion.install "completions/_f5xcctl"
        fish_completion.install "completions/f5xcctl.fish"
      end
    end
  end

  test do
    system "#{bin}/f5xcctl", "version"
  end
end
