# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class F5xcctl < Formula
  desc "kubectl-style CLI for F5 Distributed Cloud"
  homepage "https://github.com/robinmordasiewicz/f5xcctl"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v0.1.2/f5xcctl_0.1.2_darwin_amd64.tar.gz"
      sha256 "8f767894cd0337496f3f4fd0c3b4aadfba947a8b50abde72360293bc7273f144"

      def install
        bin.install "f5xcctl"
        bash_completion.install "completions/f5xcctl.bash" => "f5xcctl"
        zsh_completion.install "completions/_f5xcctl"
        fish_completion.install "completions/f5xcctl.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v0.1.2/f5xcctl_0.1.2_darwin_arm64.tar.gz"
      sha256 "52251b0dde78f50500bc78489204d235fe6535be4774241ae18b14f200c3275b"

      def install
        bin.install "f5xcctl"
        bash_completion.install "completions/f5xcctl.bash" => "f5xcctl"
        zsh_completion.install "completions/_f5xcctl"
        fish_completion.install "completions/f5xcctl.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v0.1.2/f5xcctl_0.1.2_linux_amd64.tar.gz"
      sha256 "5f0fe89cd151dc7cec3260e881163ceb8c204dd39e48bcf63c6bb6f18205d598"
      def install
        bin.install "f5xcctl"
        bash_completion.install "completions/f5xcctl.bash" => "f5xcctl"
        zsh_completion.install "completions/_f5xcctl"
        fish_completion.install "completions/f5xcctl.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/f5xcctl/releases/download/v0.1.2/f5xcctl_0.1.2_linux_arm64.tar.gz"
      sha256 "0bd4894eb852430385978900d243d88483a7e4b5f4ef482384bc431de5672df9"
      def install
        bin.install "f5xcctl"
        bash_completion.install "completions/f5xcctl.bash" => "f5xcctl"
        zsh_completion.install "completions/_f5xcctl"
        fish_completion.install "completions/f5xcctl.fish"
      end
    end
  end

  test do
    system "#{bin}/f5xcctl", "version"
  end
end
