# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vesctl < Formula
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://github.com/robinmordasiewicz/vesctl"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v1.0.0/vesctl_1.0.0_darwin_amd64.tar.gz"
      sha256 "ac8a9c90bf41b0c547871ac126a45d6847b58e89a406009e867b06225d9970e7"

      def install
        bin.install "vesctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v1.0.0/vesctl_1.0.0_darwin_arm64.tar.gz"
      sha256 "02ef4dfec17fff86818decfd946b9a6a3680bbbdddfabd576829cc6f74bb0b48"

      def install
        bin.install "vesctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v1.0.0/vesctl_1.0.0_linux_amd64.tar.gz"
      sha256 "8404fc68430d4aa3a05986fdc96bb158c4baed5c156d7f3d9248a8119b62e9ad"
      def install
        bin.install "vesctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v1.0.0/vesctl_1.0.0_linux_arm64.tar.gz"
      sha256 "cb14e4ccbabf369dd6ab4b969e2fb072147c45422cb701756f1b0c2af5a0f7b1"
      def install
        bin.install "vesctl"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with vesctl:
        1. Configure authentication: vesctl configure
        2. List namespaces: vesctl configuration list namespace
        3. Get help: vesctl --help
    EOS
  end

  test do
    system "#{bin}/vesctl", "version"
  end
end
