# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vesctl < Formula
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://github.com/robinmordasiewicz/vesctl"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v1.3.0/vesctl_1.3.0_darwin_amd64.tar.gz"
      sha256 "24770287cbc13d33a65961d8b7a2af0968dbead1b50328419a6528bc960271d5"

      def install
        bin.install "vesctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v1.3.0/vesctl_1.3.0_darwin_arm64.tar.gz"
      sha256 "0e5a806effcff2ccd395a4273abcdb93a41b928efff064bf3afe71fd28137d3a"

      def install
        bin.install "vesctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v1.3.0/vesctl_1.3.0_linux_amd64.tar.gz"
      sha256 "25de8201f35467316f454c383dea32620987670b19b054e3986a5d72e5fcea66"
      def install
        bin.install "vesctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v1.3.0/vesctl_1.3.0_linux_arm64.tar.gz"
      sha256 "854d22da0628c470dbf8afce98cded40d5e89d29e03d5c51ed7a22ae95ec2473"
      def install
        bin.install "vesctl"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with vesctl:
        1. Configure authentication: vesctl configure
        2. List namespaces: vesctl configuration list namespace
        3. Get help: vesctl --help
    EOS
  end

  test do
    system "#{bin}/vesctl", "version"
  end
end
