# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vesctl < Formula
  desc "Command-line interface for F5 Distributed Cloud"
  homepage "https://github.com/robinmordasiewicz/vesctl"
  version "4.8.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v4.8.3/vesctl_4.8.3_darwin_amd64.tar.gz"
      sha256 "c0b033c87589619677c39f3157a4c482f5b23efe278a9dc334a03c10b97cd58a"

      def install
        bin.install "vesctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v4.8.3/vesctl_4.8.3_darwin_arm64.tar.gz"
      sha256 "319db3cd762884fdb6e60997d3136af569e7c7ff015f488a28b42071dfcfcf20"

      def install
        bin.install "vesctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v4.8.3/vesctl_4.8.3_linux_amd64.tar.gz"
      sha256 "5667d11202a2bd772b82aeb704729892759d49d8b74975e8229e12a733dc3e1a"
      def install
        bin.install "vesctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robinmordasiewicz/vesctl/releases/download/v4.8.3/vesctl_4.8.3_linux_arm64.tar.gz"
      sha256 "cb3ec88218e644c134af52fcb60968eed200b02ad7f5320efc443595f8061fc6"
      def install
        bin.install "vesctl"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with vesctl:
        1. Configure authentication: vesctl configure
        2. List namespaces: vesctl configuration list namespace
        3. Get help: vesctl --help
    EOS
  end

  test do
    system "#{bin}/vesctl", "version"
  end
end
